name: Bug report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. :slightly_smiling_face:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: "I am able to reproduce the bug with the [latest version](https://github.com/mvmike/min-cal-widget/releases/latest)."
          required: true
        - label: "I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I will take the time to fill in all the required details. I understand that the bug report could be dismissed otherwise."
          required: true
        - label: "This issue contains only one bug."
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Tap on ...
        3. Open ...
        4. Place...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Affected app version
      placeholder: "x.xx.xx - Can be seen in the settings, section 'About'"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "Manufacturer and model"
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: "Can be seen in phone settings - about"
    validations:
      required: true
  - type: input
    id: launcher
    attributes:
      label: Launcher
      placeholder: "Launcher and its version"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context and screenshots
      description: |
        Add any other context like logcat (which will significantly increase the probability of me being able to fix the issue) and screenshots about the problem here.
        Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs.
        Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false