name: Bug report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. :slightly_smiling_face:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered (either open or closed)
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Tap on ...
        3. Open ...
        4. Place...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device Configuration
      description: |
        Describe your device configuration as precise as possible.
      value: |
        - MinCal version:
        - Device:
        - Android version:
        - Launcher:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context and screenshots
      description: |
        Add any other context like logcat (which will significantly increase the probability of me being able to fix the issue) and screenshots about the problem here.
        Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs.
        Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false