# https://github.com/actions
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint-test-assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: lint
      - run: ./gradlew lintKotlin

      - name: test
      - run: ./gradlew clean testRelease

      - name: assemble
      - run: ./gradlew assembleRelease